travis:
  secure:
    BINSTAR_TOKEN: H2n4QcMwWm9jnWN9/wKv8xhV72Rr0t7rhtfkwoHnX/fJ1BaZ0Y7vHuImeWnhwOm1YZ8yeeZGk1/e54nI9tAsbHIVa1PeJheuuq5SFYS8dkUa95xkeuOi2J/jiLVbLOmtyrWCGvgx/Tc+5nkKbSYIca2vdcJxjsSiJ0FX6y3Mfda5U7WewXdtSzZG0O+Aht8yXeI8Rr5U/KYH8CJpuWX8GSkhnMB9kmUQZCmlvXhcqsFbEoxhmYbqrhP4pImNoXW+FytQP8IoKb4Q5G8PV6HsFBIaIfccR0hOXVcXQ9IZS31/evoFvUU1g/FHXra2OcE7OI9ebNEEzeOjQLZgWDbQb72b74581dWKWFegOgZl/MlVKp1N+lL5ywyGW/xucUgOGMavBCYkbdPfNeTzWG7QIOJCu2nykL+D5fg0CI+vr6MkU4dLkZu7HlJAR+kDN8KNOCqSnBQx+7BWGITMCNk/y63vNj79QdH38EyIKbrM8dFrrvFL4VTg9nZ8motvwRfp0QY+jCXyt3Ir2So3Nv6uuCMUea8PdJMzZWqEXy83xiIB58VNVj9inMQcILWKMSUkgdWkb3y0B+CJL/izxcdRYEIcIvJNIdY+fUySPurz2QYWMiNmpz+inJwhLQ2E3jPgp3T0gHz59XAaQrVNibnBSIYEowk7Mm0QQokvViqZSz4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
